from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam
import numpy as np
import tensorflow as tf

class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer
        trained_model = models.load_model('results/basic_model_15_epochs_timestamp_1771301641.keras')
        self._randomize_layers(trained_model)
        trained_model.trainable = False

        trained_model.pop()
        self.model = Sequential()
        self.model.add(trained_model)

        self.model.add(layers.Dense(categories_count, activation='softmax'))
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer = RMSprop(learning_rate=0.001),
            loss = 'categorical_crossentropy',
            metrics = ['accuracy']
        )

    @staticmethod
    def _randomize_layers(model):
        # Your code goes here

        # you can write a function here to set the weights to a random value
        # use this function in _define_model to randomize the weights of your loaded model
        for layer in model.layers:
            if hasattr(layer, 'kernel_initializer') and layer.kernel is not None:
                # Reset kernel weights
                initializer = layer.kernel_initializer
                new_kernel = initializer(shape = layer.kernel.shape)
                layer.kernel.assign(new_kernel)
            if hasattr(layer, 'bias_initializer') and layer.bias is not None:
                # Reset bias weights
                initializer = layer.bias_initializer
                new_bias = initializer(shape = layer.bias.shape)
                layer.bias.assign(new_bias)
